project:
  type: website
  render:
    - about.qmd       
    - education.qmd  
    - interests.qmd  
    - cv.qmd
    - index.qmd
    - posts/*

website:
  title: "Toni Shoyinka"
  navbar:
    background: maroon
    right:
      - href: index.qmd
        text: "Blog Posts"
      - about.qmd
      - education.qmd
      - interests.qmd
      - cv.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/oluwatoni-shoyinka-90b251235/
      - icon: envelope
        aria-label: email

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual


